package resolvers

// This file will be automatically regenerated based on the schema; resolver
// implementations are copied through when regenerating.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"time"

	"eventify/api/internal/domain"
	"eventify/api/internal/features/events"
	"eventify/api/internal/transport/graphql/generated"
	gqlmiddleware "eventify/api/internal/transport/graphql/middleware"
	"eventify/api/internal/transport/graphql/models"
	"eventify/platform/apperrors"

	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

const rfc3339 = "2006-01-02T15:04:05Z07:00"

// gqlError renders a transport-agnostic error as a GraphQL error carrying a
// machine-readable `code` extension.
//
// GraphQL has no status codes; it answers 200 with an `errors` array. This is
// the third mapping of apperrors.Kind, alongside httperr.Status and
// handlers.grpcError. All three read the same Kind off the same handler — which
// is exactly why a handler must never return an HTTP status.
func gqlError(err error) error {
	var code string
	switch apperrors.KindOf(err) {
	case apperrors.NotFound:
		code = "NOT_FOUND"
	case apperrors.Invalid:
		code = "BAD_USER_INPUT"
	case apperrors.Conflict:
		code = "CONFLICT"
	case apperrors.Unauthorized:
		code = "UNAUTHENTICATED"
	case apperrors.Forbidden:
		code = "FORBIDDEN"
	case apperrors.Internal:
		return &gqlerror.Error{Message: "internal error", Extensions: map[string]any{"code": "INTERNAL"}}
	default:
		return &gqlerror.Error{Message: "internal error", Extensions: map[string]any{"code": "INTERNAL"}}
	}
	return &gqlerror.Error{Message: err.Error(), Extensions: map[string]any{"code": code}}
}

// ---- Event field resolvers -------------------------------------------------

func (r *eventResolver) ID(_ context.Context, obj *domain.Event) (string, error) {
	return obj.ID.String(), nil
}

func (r *eventResolver) Date(_ context.Context, obj *domain.Event) (string, error) {
	return obj.Date.Format(rfc3339), nil
}

func (r *eventResolver) CreatedBy(_ context.Context, obj *domain.Event) (string, error) {
	return obj.CreatedBy.String(), nil
}

func (r *eventResolver) CreatedAt(_ context.Context, obj *domain.Event) (string, error) {
	return obj.CreatedAt.Format(rfc3339), nil
}

func (r *eventResolver) UpdatedAt(_ context.Context, obj *domain.Event) (*string, error) {
	if obj.UpdatedAt == nil {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(rfc3339)
	return &s, nil
}

// ---- Mutations -------------------------------------------------------------

func (r *mutationResolver) CreateEvent(ctx context.Context, input models.CreateEventInput) (*models.CreateEventResponse, error) {
	claims, ok := gqlmiddleware.Claims(ctx)
	if !ok {
		return nil, gqlError(apperrors.New(apperrors.Unauthorized, "authentication required"))
	}

	date, err := time.Parse(rfc3339, input.Date)
	if err != nil {
		return nil, gqlError(apperrors.New(apperrors.Invalid, "date must be RFC3339"))
	}

	res, err := r.Create.Handle(ctx, events.CreateEventCommand{
		Name: input.Name, Description: input.Description, Date: date,
		Location: input.Location, Organizer: input.Organizer, Category: input.Category,
		Tags: input.Tags, Capacity: input.Capacity,
		// From the token, not uuid.New().
		CreatedBy: claims.UserID,
	})
	if err != nil {
		return nil, gqlError(err)
	}
	return &models.CreateEventResponse{EventID: res.EventID.String(), Message: "event created"}, nil
}

func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input models.UpdateEventInput) (*models.UpdateEventResponse, error) {
	if _, ok := gqlmiddleware.Claims(ctx); !ok {
		return nil, gqlError(apperrors.New(apperrors.Unauthorized, "authentication required"))
	}

	eventID, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlError(apperrors.New(apperrors.Invalid, "invalid event id"))
	}

	// UpdateEventInput is a patch — every field is optional — but the command is
	// total. Read the current row, apply the patch, then write. The read goes
	// through the Get handler rather than a second SQL statement here, because
	// this file is a transport adapter and must contain no SQL.
	current, err := r.Get.Handle(ctx, events.GetEventQuery{EventID: eventID})
	if err != nil {
		return nil, gqlError(err)
	}

	cmd := events.UpdateEventCommand{
		EventID:     eventID,
		Name:        current.Name,
		Description: current.Description,
		Date:        current.Date,
		Location:    current.Location,
		Organizer:   current.Organizer,
		Category:    current.Category,
		Tags:        current.Tags,
		Capacity:    current.Capacity,
	}
	if input.Name != nil {
		cmd.Name = *input.Name
	}
	if input.Description != nil {
		cmd.Description = *input.Description
	}
	if input.Date != nil {
		d, err := time.Parse(rfc3339, *input.Date)
		if err != nil {
			return nil, gqlError(apperrors.New(apperrors.Invalid, "date must be RFC3339"))
		}
		cmd.Date = d
	}
	if input.Location != nil {
		cmd.Location = *input.Location
	}
	if input.Organizer != nil {
		cmd.Organizer = *input.Organizer
	}
	if input.Category != nil {
		cmd.Category = *input.Category
	}
	if input.Tags != nil {
		cmd.Tags = input.Tags
	}
	if input.Capacity != nil {
		cmd.Capacity = *input.Capacity
	}

	if _, err := r.Update.Handle(ctx, cmd); err != nil {
		return nil, gqlError(err)
	}

	updated, err := r.Get.Handle(ctx, events.GetEventQuery{EventID: eventID})
	if err != nil {
		return nil, gqlError(err)
	}
	return &models.UpdateEventResponse{Event: &updated, Message: "event updated"}, nil
}

func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (*models.DeleteEventResponse, error) {
	if _, ok := gqlmiddleware.Claims(ctx); !ok {
		return nil, gqlError(apperrors.New(apperrors.Unauthorized, "authentication required"))
	}

	eventID, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlError(apperrors.New(apperrors.Invalid, "invalid event id"))
	}

	if err := r.Delete.Handle(ctx, events.DeleteEventCommand{EventID: eventID}); err != nil {
		return nil, gqlError(err)
	}
	return &models.DeleteEventResponse{Message: "event deleted"}, nil
}

// ---- Queries ---------------------------------------------------------------

func (r *queryResolver) Event(ctx context.Context, id string) (*domain.Event, error) {
	eventID, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlError(apperrors.New(apperrors.Invalid, "invalid event id"))
	}

	e, err := r.Get.Handle(ctx, events.GetEventQuery{EventID: eventID})
	if err != nil {
		if apperrors.KindOf(err) == apperrors.NotFound {
			// `event(id:)` is nullable in the schema: a miss is null, not an error.
			return nil, nil
		}
		return nil, gqlError(err)
	}
	return &e, nil
}

func (r *queryResolver) Events(ctx context.Context, page *int, limit *int) (*models.ListEventsResponse, error) {
	p, l := 1, 10
	if page != nil && *page > 0 {
		p = *page
	}
	if limit != nil && *limit > 0 {
		l = *limit
	}

	// The old resolver called GetAllEvents, which SELECTed every row in the
	// table, reported len(events) as the total, and ignored page and limit
	// entirely. Paging happens in SQL now.
	res, err := r.List.Handle(ctx, events.GetEventsQuery{Limit: l, Offset: (p - 1) * l})
	if err != nil {
		return nil, gqlError(err)
	}

	out := make([]*domain.Event, 0, len(res.Events))
	for i := range res.Events {
		out = append(out, &res.Events[i])
	}
	return &models.ListEventsResponse{Events: out, Total: res.Total, Page: p, Limit: l}, nil
}

// ---- User field resolvers --------------------------------------------------

func (r *userResolver) ID(_ context.Context, obj *domain.User) (string, error) {
	return obj.ID.String(), nil
}

func (r *userResolver) CreatedAt(_ context.Context, obj *domain.User) (string, error) {
	return obj.CreatedAt.Format(rfc3339), nil
}

func (r *userResolver) UpdatedAt(_ context.Context, obj *domain.User) (*string, error) {
	if obj.UpdatedAt == nil {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(rfc3339)
	return &s, nil
}

// ---- gqlgen plumbing -------------------------------------------------------

func (r *Resolver) Event() generated.EventResolver       { return &eventResolver{r} }
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }
func (r *Resolver) Query() generated.QueryResolver       { return &queryResolver{r} }
func (r *Resolver) User() generated.UserResolver         { return &userResolver{r} }

type eventResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
