// Package models holds the GraphQL input and payload types.
//
// Everything else in this package is generated by gqlgen from
// api/internal/transport/graphql/schemas/. This file exists only to carry the
// package comment, so that regenerating models_gen.go cannot drop it.
package models
