// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/event_service.go

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	domain "eventify/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIEventService is a mock of IEventService interface.
type MockIEventService struct {
	ctrl     *gomock.Controller
	recorder *MockIEventServiceMockRecorder
}

// MockIEventServiceMockRecorder is the mock recorder for MockIEventService.
type MockIEventServiceMockRecorder struct {
	mock *MockIEventService
}

// NewMockIEventService creates a new mock instance.
func NewMockIEventService(ctrl *gomock.Controller) *MockIEventService {
	mock := &MockIEventService{ctrl: ctrl}
	mock.recorder = &MockIEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEventService) EXPECT() *MockIEventServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockIEventService) CreateEvent(event *domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockIEventServiceMockRecorder) CreateEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockIEventService)(nil).CreateEvent), event)
}

// DeleteEvent mocks base method.
func (m *MockIEventService) DeleteEvent(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockIEventServiceMockRecorder) DeleteEvent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockIEventService)(nil).DeleteEvent), id)
}

// GetAllEvents mocks base method.
func (m *MockIEventService) GetAllEvents() []domain.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEvents")
	ret0, _ := ret[0].([]domain.Event)
	return ret0
}

// GetAllEvents indicates an expected call of GetAllEvents.
func (mr *MockIEventServiceMockRecorder) GetAllEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEvents", reflect.TypeOf((*MockIEventService)(nil).GetAllEvents))
}

// GetEventById mocks base method.
func (m *MockIEventService) GetEventById(id uuid.UUID) *domain.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventById", id)
	ret0, _ := ret[0].(*domain.Event)
	return ret0
}

// GetEventById indicates an expected call of GetEventById.
func (mr *MockIEventServiceMockRecorder) GetEventById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventById", reflect.TypeOf((*MockIEventService)(nil).GetEventById), id)
}

// UpdateEvent mocks base method.
func (m *MockIEventService) UpdateEvent(event *domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockIEventServiceMockRecorder) UpdateEvent(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockIEventService)(nil).UpdateEvent), event)
}
