// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"eventify/internal/domain"
)

type CreateEventInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Date        string   `json:"date"`
	Location    string   `json:"location"`
	Organizer   string   `json:"organizer"`
	Category    string   `json:"category"`
	Tags        []string `json:"tags"`
	Capacity    int      `json:"capacity"`
}

type CreateEventResponse struct {
	EventID string `json:"eventId"`
	Message string `json:"message"`
}

type DeleteEventResponse struct {
	Message string `json:"message"`
}

type ListEventsResponse struct {
	Events []*domain.Event `json:"events"`
	Total  int             `json:"total"`
	Page   int             `json:"page"`
	Limit  int             `json:"limit"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateEventInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Date        *string  `json:"date,omitempty"`
	Location    *string  `json:"location,omitempty"`
	Organizer   *string  `json:"organizer,omitempty"`
	Category    *string  `json:"category,omitempty"`
	Tags        []string `json:"tags,omitempty"`
	Capacity    *int     `json:"capacity,omitempty"`
}

type UpdateEventResponse struct {
	Event   *domain.Event `json:"event"`
	Message string        `json:"message"`
}
